baseURL = "https://leonzym.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "LEON"                        # site title                     # 网站标题
theme = "cream"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 10                           # shows the number of articles   # 首页显示文章数量
rssLimit = 10                           # limit the number of posts in rss output
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Google统计代码
disqusShortname = ""                   # your discuss shortname         # Disqus评论系统代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "Leon"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "Categories"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about/"

[params]
  subTitle = ""                                       # site's subTitle              # 网站二级标题
  footerSlogan = "学过建筑 | 在写代码 | 喜欢拍照"                                   # site's footer slogan         # 网站页脚标语
  keywords = ["Leon", "Blog", "Post", "Frontend", "Life"]                                   # site's keywords              # 网站关键字
  description = "Leon's personal blog about life & frontend"                        # site's description           # 网站描述
  enableMathJax = false                                                 # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "zfq7GkBtKpYLeVhC7CKBB4JG-gzGzoHsz"
  appKey = "eiLbXy1Pu4Wwbq6OUDoQHSDk"
  placeholder = ""
  avatar = "retro"       # see optional value in https://valine.js.org/avatar.html
  meta = ["nick"]        # commenter's info, ['nick','mail','link']

# Your socail's url
# 社交地址配置
[social]
  github = "https://github.com/Leon-zym/"
  instagram = "https://www.instagram.com/leon.zym/"
  weibo = "https://weibo.com/u/6634867195/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
